"""Replace ActivityCompletion with ActivityInstance

Revision ID: ade3f5272562
Revises: dccf76ec4859
Create Date: 2024-09-15 13:40:54.892449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade3f5272562'
down_revision = 'dccf76ec4859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_activity_id', sa.Integer(), nullable=False),
    sa.Column('instance_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mood', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_activity_id'], ['schedule_activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('activity_completions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_completions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('schedule_activity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completion_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('mood', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['schedule_activity_id'], ['schedule_activities.id'], name='activity_completions_schedule_activity_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='activity_completions_pkey')
    )
    op.drop_table('activity_instances')
    # ### end Alembic commands ###
