"""Add timezone to User model

Revision ID: c14a313a3340
Revises: 82d331a7e91c
Create Date: 2024-09-15 09:18:09.931077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c14a313a3340'
down_revision = '82d331a7e91c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_activities', schema=None) as batch_op:
        batch_op.drop_column('start_time')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    with op.batch_alter_table('schedule_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
